### ISSUE TITLE
Missing requirements.txt?

### ISSUE THREAD

**Issue by burningion** [yangchris11/samurai#1]
Thanks for the work! 

In the main README.md, you make reference to a requirements.txt (with a `pip install requirements.txt`), but it appears that wasn't included in the repository.

Maybe that was supposed to be committed but got left out?

**Comment by yangchris11** [comment]
Thank you for point out the missing requirements!

We had replaced the line a list of packages to install for now.

**Comment by yangchris11** [comment]
Thank you for point out the missing requirements!

We had replaced the line with a list of packages to install for now.
