### ISSUE TITLE
Minimum frame rate?

### ISSUE THREAD

**Issue by cinjon** [yangchris11/samurai#10]
Hi, what's the minimum frame rate for which SAMURAI works well?

**Comment by yangchris11** [comment]
I think it will depends on the characteristic of the video sequence and the object that you are trying to track.

For reference, most of the VOT dataset we benchmarked are either 30fps (e.g., LaSOT, LaSOT-ext) or 10fps (GOT-10k).

Also, the SAM 2 was trained and evaluated on [24 fps videos of SA-V val and test](https://github.com/facebookresearch/sam2/blob/main/sav_dataset/README.md).

**Comment by Tetsujinfr** [comment]
Framerate does not impact the SAM2 results per say, provided that there is no, or limited, motion blur in the video frames. With high motion blur SAM2 performance collapses (like any computer vision model tbh).
