### ISSUE TITLE
issue when building docker

### ISSUE THREAD

**Issue by amansaikrishna** [yangchris11/samurai#16]
Traceback (most recent call last):
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 644, in _locate
backend-1   |     obj = getattr(obj, part)
backend-1   | AttributeError: module 'sam2' has no attribute 'sam2_video_predictor'
backend-1   |
backend-1   | During handling of the above exception, another exception occurred:
backend-1   |
backend-1   | Traceback (most recent call last):
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 650, in _locate
backend-1   |     obj = import_module(mod)
backend-1   |   File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
backend-1   |     return _bootstrap._gcd_import(name[level:], package, level)
backend-1   |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
backend-1   |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
backend-1   |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
backend-1   |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
backend-1   |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
backend-1   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-1   |   File "/opt/sam2/server/sam2/sam2_video_predictor.py", line 14, in <module>
backend-1   |     from sam2.modeling.sam2_base import NO_OBJ_SCORE, SAM2Base
backend-1   |   File "/opt/sam2/server/sam2/modeling/sam2_base.py", line 20, in <module>
backend-1   |     from sam2.utils.kalman_filter import KalmanFilter
backend-1   |   File "/opt/sam2/server/sam2/utils/kalman_filter.py", line 2, in <module>
backend-1   |     import scipy.linalg
backend-1   | ModuleNotFoundError: No module named 'scipy'
backend-1   |
backend-1   | The above exception was the direct cause of the following exception:
backend-1   |
backend-1   | Traceback (most recent call last):
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
backend-1   |     target = _locate(target)
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/utils.py", line 653, in _locate
backend-1   |     raise ImportError(
backend-1   | ImportError: Error loading 'sam2.sam2_video_predictor.SAM2VideoPredictor':
backend-1   | ModuleNotFoundError("No module named 'scipy'")
backend-1   | Are you sure that 'sam2_video_predictor' is importable from module 'sam2'?
backend-1   |
backend-1   | The above exception was the direct cause of the following exception:
backend-1   |
backend-1   | Traceback (most recent call last):
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
backend-1   |     worker.init_process()
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/gthread.py", line 94, in init_process
backend-1   |     super().init_process()
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 135, in init_process
backend-1   |     self.load_wsgi()
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
backend-1   |     self.wsgi = self.app.wsgi()
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/base.py", line 66, in wsgi
backend-1   |     self.callable = self.load()
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 57, in load
backend-1   |     return self.load_wsgiapp()
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/gunicorn/app/wsgiapp.py", line 47, in load_wsgiapp
backend-1   |     return util.import_app(self.app_uri)
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/gunicorn/util.py", line 370, in import_app
backend-1   |     mod = importlib.import_module(module)
backend-1   |   File "/opt/conda/lib/python3.10/importlib/__init__.py", line 126, in import_module
backend-1   |     return _bootstrap._gcd_import(name[level:], package, level)
backend-1   |   File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
backend-1   |   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
backend-1   |   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
backend-1   |   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
backend-1   |   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
backend-1   |   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
backend-1   |   File "/opt/sam2/server/app.py", line 35, in <module>
backend-1   |     inference_api = InferenceAPI()
backend-1   |   File "/opt/sam2/server/inference/predictor.py", line 89, in __init__
backend-1   |     self.predictor = build_sam2_video_predictor(
backend-1   |   File "/opt/sam2/server/sam2/build_sam.py", line 129, in build_sam2_video_predictor
backend-1   |     model = instantiate(cfg.model, _recursive_=True)
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
backend-1   |     return instantiate_node(
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
backend-1   |     _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
backend-1   |   File "/opt/conda/lib/python3.10/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
backend-1   |     raise InstantiationException(msg) from e
backend-1   | hydra.errors.InstantiationException: Error locating target 'sam2.sam2_video_predictor.SAM2VideoPredictor', set env var HYDRA_FULL_ERROR=1 to see chained exception.
backend-1   | full_key: model
backend-1   | [2024-11-25 05:39:52 +0000] [8] [INFO] Worker exiting (pid: 8)
backend-1   | [2024-11-25 05:39:52 +0000] [7] [ERROR] Worker (pid:8) exited with code 3
backend-1   | [2024-11-25 05:39:52 +0000] [7] [ERROR] Shutting down: Master
backend-1   | [2024-11-25 05:39:52 +0000] [7] [ERROR] Reason: Worker failed to boot.

**Comment by lingtengqiu** [comment]
+1

**Comment by yangchris11** [comment]
The Docker file currently located in the sam2 folder is identical to the one from the [original repository](https://github.com/facebookresearch/sam2). We have not yet provided support or made any necessary modifications to it.

However, from the error message, it seems like it is missing the additional packages required to run samurai, you may try to update the docker accordingly.
