### ISSUE TITLE
Prep data sample

### ISSUE THREAD

**Issue by vitalik** [yangchris11/samurai#2]
Could you also commit/uplaod your sample somehwere so it is easy to quickly test check performance and usage

```
data/LaSOT
├── airplane/
│   ├── airplane-1/
│   │   ├── full_occlusion.txt
│   │   ├── groundtruth.txt
│   │   ├── img
│   │   ├── nlp.txt
│   │   └── out_of_view.txt
│   ├── airplane-2/
│   ├── airplane-3/
│   ├── ...
├── basketball
├── bear
├── bicycle
...
├── training_set.txt
└── testing_set.txt
```

**Comment by yangchris11** [comment]
To get a quick start on the VOT dataset, I recommend following the hugging face dataset cards prepare by the original author:

- [LaSOT](https://huggingface.co/datasets/l-lt/LaSOT) 
- [LaSOT-ext](https://huggingface.co/datasets/l-lt/LaSOT-ext)

they provided download script and setup information that we also followed.

**Comment by yangchris11** [comment]
We also provide a `script/demo.py` to inference on your own video, please check out!

**Comment by gjhhust** [comment]
> We also provide a `script/demo.py` to inference on your own video, please check out!

Hello, I would like to know where is training_set.txt and test_test.txt?
