### ISSUE TITLE
Segmentation fault (core dumped) when main_inference

### ISSUE THREAD

**Issue by laisimiao** [yangchris11/samurai#20]
![image](https://github.com/user-attachments/assets/c25aefbf-8bbe-4ae4-9bc6-31b2cc39c68e)

After installing the env successfully, run `python scripts/main_inference.py ` would incur **Segmentation fault (core dumped)**. What's the possible reasons and how to solve them?

**Comment by rese1f** [comment]
hi we never meet this issue before, but as for my experience, its probably due to the wrong version of pytorch and cuda you've installed, you can do a double check :)

**Comment by yangchris11** [comment]
Close for now, reopen if needed
