### ISSUE TITLE
Running without cuda

### ISSUE THREAD

**Issue by mirosaide** [yangchris11/samurai#22]
Those running without cuda:

`predictor = build_sam2_video_predictor(model_cfg, checkpoint, device="cpu")`

**Comment by zhyjiang** [comment]
Could you provide more details about your question? Are you inquiring about support for CPU inference?

**Comment by zhyjiang** [comment]
SAMURAI is based on SAM2. Maybe you can check this  https://github.com/facebookresearch/sam2/issues/71.

**Comment by csparker247** [comment]
I just did this today, and it is supported with some small changes to `demo.py`. First, install SAM2 with the `SAM2_BUILD_CUDA=0` environment variable as mentioned in the SAM2 documentation [here](https://github.com/facebookresearch/sam2/blob/main/INSTALL.md).

Then you need to edit this line from `device="cuda:0"` to `device="cpu"`:
https://github.com/yangchris11/samurai/blob/d1359707f0c7f0ab56e061cc8c3a6447c446b01f/scripts/demo.py#L44

I also tried changing the `device_type` to `cpu` for the `torch.autocast` on L72, but this caused a bunch of cascading errors for me. I ended it up leaving it as `cuda`, and PyTorch complained, but everything still ran.

**Comment by mirosaide** [comment]
Well, actually I was putting for those who might get an error due to cuda.

**Comment by csparker247** [comment]
> Well, actually I was putting for those who might get an error due to cuda.

Yes, I think your OP was interpreted as a question rather than advice, and since I had just happened to do the same thing, I expanded for clarity.
