### ISSUE TITLE
Demo on custom video not working

### ISSUE THREAD

**Issue by learner524** [yangchris11/samurai#28]
I am trying to use this on Google Colab: [[Samurai Notebook](https://colab.research.google.com/github/koji/GoogleColab/blob/main/Samurai.ipynb#scrollTo=aLhHflOFcPpC)](https://colab.research.google.com/github/koji/GoogleColab/blob/main/Samurai.ipynb#scrollTo=aLhHflOFcPpC). While running `scripts/demo.py`, it shows `^C` and exits abruptly.  

Steps I have taken:  
1. Installed the requirements and set up the project.  
2. Uploaded a custom video and a text file in the format `xywh`, then ran the demo command.  

![image](https://github.com/user-attachments/assets/3854139e-3ced-401c-8520-ad5a12a79634)

**Comment by mdaniyal214** [comment]
Facing same issue

**Comment by mdaniyal214** [comment]
Infact! when I trimmed the video further, it ran. Seems like some issue with the video size.

**Comment by yangchris11** [comment]
We have not yet got a chance to test it on google colab yet, according to @mdaniyal214's comment, it seems like it may be the memory limitation of google colab.
