### ISSUE TITLE
Labelling tool

### ISSUE THREAD

**Issue by mirosaide** [yangchris11/samurai#30]
Could you suggest labelling tools, I am using this one: [https://github.com/drainingsun/ybat/tree/master](url). I run a demo video for plate detection, people and tank, I didn't work at all. I took the video and strip in to frames, took the first frame annotate the coordinates for each case above. and then use the custom script. The output does contain any object tracking.

**Comment by hsiangwei0903** [comment]
You can try to use this to find the bounding box coordinate for the first frame. Remember to convert to xywh format.
https://pixspy.com/

**Comment by CVHub520** [comment]
Hi @mirosaide; I'd like to suggest that you consider trying out this [tool](https://github.com/CVHub520/X-AnyLabeling/blob/main/examples/interactive_video_object_segmentation/README.md), which appears to be a promising alternative for your needs.
