### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by wangyujie615** [yangchris11/samurai#34]
Hello, in the paper, I did not find a description of the training process for the model. Does this mean the proposed method does not involve training the entire model?

**Comment by XuM007** [comment]
Thank you for your excellent work. After reading the paper, I also have similar questions. The paper indicates that it can perform zero-shot on the VOT datasets. However, does the entire model need to be trained for the newly added Motion Modeling and Motion-Aware Memory Selection? When running the demo, I noticed that it directly uses the weights from SAM2. Does the Kalman Filter not require training? Looking forward to your reply.

**Comment by yangchris11** [comment]
Yes, it is a zero-shot method, we directly use the weights from SAM 2.1 to conduct VOT experiments.

Kalman filter is used to estimate the current and future state (bounding box location and scale in our case) of a moving object based on measurements over time, it is a common approach that had been adapt in the field of tracking for a long time which does not requires any training. Please refer to [code](https://github.com/yangchris11/samurai/blob/master/sam2/sam2/utils/kalman_filter.py) for more detail.
