### ISSUE TITLE
use real-rtsp stream as input

### ISSUE THREAD

**Issue by vamsi-krishna-mishran** [yangchris11/samurai#35]
The code is in a way that it accepts a video as input, but I am looking to give my webcam as input and see the resulting frame by frame. how is it possible?

**Comment by rese1f** [comment]
Technically, this is feasible. Our method only requires an initial bounding box (bbox) as reference, after which it performs inference on the video. You can try modifying the I/O part to meet your requirements.

**Comment by zhyjiang** [comment]
You can refer to this issue: #12
