### ISSUE TITLE
init_state failed for 1080P video

### ISSUE THREAD

**Issue by wuhongsheng** [yangchris11/samurai#38]
python scripts/demo.py --video_path /tmp/output2.mp4 --txt_path /tmp/first_frame_bbox.txt
SAMURAI mode: True
1080 1920
1983148141
init state
Killed

**Comment by richieling** [comment]
I think it's because the system ran out of memory on the RAM. Shortened the video and able to see
`propagate in video`

**Comment by rese1f** [comment]
also see issue https://github.com/yangchris11/samurai/issues/41
