### ISSUE TITLE
img or video miss match

### ISSUE THREAD

**Issue by mirosaide** [yangchris11/samurai#4]
I downloaded the data to test both for planes and tank. For both of them I always get the same error:

`(sam2) (base) MacBook-Air samurai-master % python scripts/main_inference.py 
Traceback (most recent call last):
  File "/SAM2/samurai-master/scripts/main_inference.py", line 57, in <module>
    cid_name = video.split('-')[1]
IndexError: list index out of range`

Note that I set the same directory structure.

**Comment by yangchris11** [comment]
Can you `ls` your folder or screenshot your folder structure? Also you might want to make sure that all the video sequences in `data/LaSOT/testing_set.txt` are properly downloaded or modify it baed on your subset of sequences.

**Comment by mirosaide** [comment]
> Can you `ls` your folder or screenshot your folder structure? Also you might want to make sure that all the video sequences in `data/LaSOT/testing_set.txt` are properly downloaded or modify it baed on your subset of sequences.

I have fixed and run the code, it works well -  I even tested it with my custom video.

**Comment by mirosaide** [comment]
> Can you `ls` your folder or screenshot your folder structure? Also you might want to make sure that all the video sequences in `data/LaSOT/testing_set.txt` are properly downloaded or modify it baed on your subset of sequences.

I have fixed the issue. It all runs smoothly now.
