### ISSUE TITLE
Isn't it supposed to handle long videos? 

### ISSUE THREAD

**Issue by tppqt** [yangchris11/samurai#40]
Why does my 32GB of memory fill up and the system become very sluggish when processing a 4-minute video, resulting in the following error?

SAMURAI mode: True
[15:18:19] D:\a\decord\decord\src\video\ffmpeg\filter_graph.cc:112: buffersink get frame failed12
Traceback (most recent call last):
  File "E:\basketball_seg\samurai\scripts\demo.py", line 142, in <module>
    main(args)
  File "E:\basketball_seg\samurai\scripts\demo.py", line 93, in main
    state = predictor.init_state(frames_or_path, offload_video_to_cpu=True)
  File "E:\basketball_seg\venv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "E:\/basketball_seg\samurai\sam2\sam2\sam2_video_predictor.py", line 53, in init_state
    images, video_height, video_width = load_video_frames(
  File "E:\/basketball_seg\samurai\sam2\sam2\utils\misc.py", line 189, in load_video_frames
    return load_video_frames_from_video_file(
  File "E:\/basketball_seg\samurai\sam2\sam2\utils\misc.py", line 298, in load_video_frames_from_video_file
    for frame in decord.VideoReader(video_path, width=image_size, height=image_size):
  File "E:\basketball_seg\venv\lib\site-packages\decord\video_reader.py", line 105, in __getitem__
    return self.next()
  File "E:\basketball_seg\venv\lib\site-packages\decord\video_reader.py", line 117, in next
    arr = _CAPI_VideoReaderNextFrame(self._handle)
  File "E:\basketball_seg\venv\lib\site-packages\decord\_ffi\_ctypes\function.py", line 173, in __call__
    check_call(_LIB.DECORDFuncCall(
  File "E:\basketball_seg\venv\lib\site-packages\decord\_ffi\base.py", line 78, in check_call
    raise DECORDError(err_str)
decord._ffi.base.DECORDError: [15:18:32] D:\a\decord\decord\src\video\ffmpeg\threaded_decoder.cc:292: [15:18:19] D:\a\decord\decord\src\video\ffmpeg\threaded_decoder.cc:159: Check failed: filter_graph_->Pop(&out_frame_p) Error fetch filtered frame.

**Comment by tppqt** [comment]
sloved! another question, I want to used flash-attn, but I run the code, it give this output below:
E:\basketball_seg\venv\lib\site-packages\torchvision\io\video_reader.py:233: UserWarning: Accurate seek is not implemented for pyav backend
  warnings.warn("Accurate seek is not implemented for pyav backend")
E:\/basketball_seg\samurai\sam2\sam2\modeling\backbones\hieradet.py:70: UserWarning: 1Torch was not compiled with flash attention. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:555.)
  x = F.scaled_dot_product_attention(
E:\/basketball_seg\samurai\sam2\sam2\sam2_video_predictor.py:971: UserWarning: cannot import name '_C' from 'sam2' (E:\/basketball_seg\samurai\sam2\sam2\__init__.py)

Skipping the post-processing step due to the error above. You can still use SAM 2 and it's OK to ignore the error above, although some post-processing functionality may be limited (which doesn't affect the results in most cases; see https://github.com/facebookresearch/sam2/blob/main/INSTALL.md).
  pred_masks_gpu = fill_holes_in_mask_scores(
propagate in video:   0%|          | 0/6000 [00:00<?, ?it/s]E:\/basketball_seg\samurai\sam2\sam2\modeling\sam\transformer.py:344: UserWarning: Memory efficient kernel not used because: (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:718.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\/basketball_seg\samurai\sam2\sam2\modeling\sam\transformer.py:344: UserWarning: Memory Efficient attention has been runtime disabled. (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen/native/transformers/sdp_utils_cpp.h:495.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\/basketball_seg\samurai\sam2\sam2\modeling\sam\transformer.py:344: UserWarning: Flash attention kernel not used because: (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:720.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\/basketball_seg\samurai\sam2\sam2\modeling\sam\transformer.py:344: UserWarning: CuDNN attention kernel not used because: (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:722.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\/basketball_seg\samurai\sam2\sam2\modeling\sam\transformer.py:344: UserWarning: Query tensor was not in cuDNN-supported packed QKV layout[1048576, 1048576, 256, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:410.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\/basketball_seg\samurai\sam2\sam2\modeling\sam\transformer.py:344: UserWarning: Key tensor was not in cuDNN-supported packed QKV layout[1048576, 256, 256, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:413.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\/basketball_seg\samurai\sam2\sam2\modeling\sam\transformer.py:344: UserWarning: Value tensor was not in cuDNN-supported packed QKV layout[1048576, 256, 256, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:416.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\/basketball_seg\samurai\sam2\sam2\modeling\sam\transformer.py:344: UserWarning: Query tensor was not in cuDNN-supported unpacked QKV layout[1048576, 1048576, 256, 1] (Triggered internally at C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\aten\src\ATen\native\transformers\cuda\sdp_utils.cpp:421.)
  out = F.scaled_dot_product_attention(q, k, v, dropout_p=dropout_p)
E:\basketball_seg\venv\lib\site-packages\torch\nn\modules\module.py:1562: UserWarning: Flash Attention kernel failed due to: No available kernel. Aborting execution.
Falling back to all available kernels for scaled_dot_product_attention (which may have a slower speed).
  return forward_call(*args, **kwargs)

**Comment by richieling** [comment]
@tppqt Hello, how did you solve the memory issue?

**Comment by hsiangwei0903** [comment]
@tppqt you can refer to this SAM2 issue https://github.com/facebookresearch/sam2/issues/48

**Comment by yangchris11** [comment]
See https://github.com/facebookresearch/sam2/issues/264 for more details on inference long videos.
