### ISSUE TITLE
Is there a memory leak?

### ISSUE THREAD

**Issue by richieling** [yangchris11/samurai#41]
Hello, I tried to run the demo.py on a custom video of approx 5 mins long. I noticed my PC RAM memory usage spiked up to >100GB, which is quite unusual. Is there a possibility of a memory leak somewhere?

I have tried on both my desktop (2080 Ti) and DGX A100 machines.

What is the expected RAM and GPU usage for running this model for inference only?

Thanks!

**Comment by MeharRamzan** [comment]
@richieling The error occurs due to storing all video frames in a single list, which leads to memory overflow. Modifying the storage type will resolve this issue.
![image](https://github.com/user-attachments/assets/1bad923e-1e07-45c4-89e7-7b7688573607)

**Comment by yangchris11** [comment]
See https://github.com/facebookresearch/sam2/issues/264 for more details on inference long videos.
