### ISSUE TITLE
Thanks for your great work! Could you please provide some details or examples about evaluation?

### ISSUE THREAD

**Issue by gjhhust** [yangchris11/samurai#42]
Thanks for your great work! Could you please provide some details or examples about evaluation?

**Comment by yangchris11** [comment]
Please refer to the official repo https://github.com/votchallenge/toolkit or this python-based evaluation toolkit https://github.com/HengLan/VastTrack/tree/main/PythonEvaluationToolkit for now, as we follow their evaluation protocol on AUC, precision and normalized precision.

Our results can be found in [[Raw Results]](https://drive.google.com/drive/folders/1ssiDmsC7mw5AiItYQG4poiR1JgRq305y?usp=sharing).

**Comment by gjhhust** [comment]
thanks！I have another question, how is the test set for LoSOT-ext divided, is there a corresponding testing_set.txt or is the entire dataset used as the test set

**Comment by yangchris11** [comment]
@gjhhust the entire LaSOT-ext is used as testing dataset (all 150 sequences).
