### ISSUE TITLE
This error will be reported as soon as the video is long

### ISSUE THREAD

**Issue by jianjiu99999** [yangchris11/samurai#43]
python scripts/demo.py --video_path /home/ubuntu/samurai/1643.mp4 --txt_path /home/ubuntu/1.txt 
SAMURAI mode: True
Traceback (most recent call last):
  File "/home/ubuntu/samurai/scripts/demo.py", line 122, in <module>
    main(args)
  File "/home/ubuntu/samurai/scripts/demo.py", line 64, in main
    height, width = loaded_frames[0].shape[:2]
IndexError: list index out of range

Thank you for reviewing my question

**Comment by lingluoyuu** [comment]
This error is caused by storing all frames of the video in one list, resulting in memory overflow. Trimming the video length and modifying the storage type can solve this problem

**Comment by yangchris11** [comment]
See https://github.com/facebookresearch/sam2/issues/264 for more details on inference long videos.
