### ISSUE TITLE
example data

### ISSUE THREAD

**Issue by mehrnia** [yangchris11/samurai#45]
Hi,
Thanks for the great work.
Have you provided the data (example data) ? 
I want to look into .txt files!
currently, data folder is empty.

**Comment by hsiangwei0903** [comment]
Please refer to our data preparation instruction. https://github.com/yangchris11/samurai?tab=readme-ov-file#data-preparation

**Comment by mehrnia** [comment]
Yes, I see this.
I mean the content of each file . a folder which includes these different files then I can open each e.g., nlp.txt and look into its content.

**Comment by nisar2** [comment]
@mehrnia did you ever figure this out?
