### ISSUE TITLE
check point

### ISSUE THREAD

**Issue by mehrnia** [yangchris11/samurai#46]
Hi, 
thank you for the great work. 
is it possible to change the checkpoint of SAM e.g., tiny, base, large,... then the SAMURAI will be adjusted accordingly?

**Comment by hsiangwei0903** [comment]
Yes, you can change the SAM2 checkpoint here https://github.com/yangchris11/samurai/blob/c8c27f7e2acc2ed0a6e3691d32530b26af2d1cb5/scripts/main_inference.py#L35

and here https://github.com/yangchris11/samurai/blob/c8c27f7e2acc2ed0a6e3691d32530b26af2d1cb5/scripts/demo.py#L118
