### ISSUE TITLE
How to port from SAM2 to SAMURAI

### ISSUE THREAD

**Issue by planetMatrix** [yangchris11/samurai#47]
@yangchris11 Absolutely marvellous and robust tracking you have achieved. Very well executed 👏👏👏

I was experimenting with SAM2 with this code. I was wondering what's the best way to port to Samurai

https://github.com/argildotai/sam2removevideobackground

**Comment by rese1f** [comment]
We don't know the details for that repo but since SAMURAI is based on SAM 2 so it should be seamless.
