### ISSUE TITLE
REAL TIME using webcam input?

### ISSUE THREAD

**Issue by samirertt** [yangchris11/samurai#49]
Hello, did anyone found a way to use samurai on webcam input realtime?

**Comment by tppqt** [comment]
The paper claims that it can achieve real-time performance with over 40 FPS, but when I tested it with Flash-Attention on an A100, I could only get a maximum of 13 FPS, and that's with the tiny model, which is far from real-time

**Comment by rese1f** [comment]
also see issue https://github.com/yangchris11/samurai/issues/12

The existing code doesn't support live/streaming video as we inherit most of the codebase from the amazing SAM 2.

Some discussion that you might be interested in: https://github.com/facebookresearch/sam2/issues/90, https://github.com/facebookresearch/sam2/issues/388#issuecomment-2419734551

**Comment by yangchris11** [comment]
Might be worthwhile to check what SAM 2 baseline run at on your machine, as it should be far more faster than that according to our experience and official SAM 2 repository for tiny model.
