### ISSUE TITLE
not enough values to unpack (expected 9, got 7)

### ISSUE THREAD

**Issue by JINNMnm** [yangchris11/samurai#51]
Amazing work!
I find that if use mask as input, this function below will be called.
https://github.com/yangchris11/samurai/blob/c8c27f7e2acc2ed0a6e3691d32530b26af2d1cb5/sam2/sam2/modeling/sam2_base.py#L902
But the sam_output didn't contain the ious and kfious. So when unpack the sam output here
https://github.com/yangchris11/samurai/blob/c8c27f7e2acc2ed0a6e3691d32530b26af2d1cb5/sam2/sam2/modeling/sam2_base.py#L1005
will raise the error

**Comment by yangchris11** [comment]
Please see https://github.com/yangchris11/samurai/issues/3 for same discussion. We currently only support bbox as input, but you can be expecting the mask prompt version soon :)

**Comment by JINNMnm** [comment]
Thanks a lot for your response.
