### ISSUE TITLE
Do I really need 230GB of data for this?

### ISSUE THREAD

**Issue by eizoxx** [yangchris11/samurai#53]
Hi all,

I have a question about the LaSOT training data. Why is it necessary to download roughly 230GB of data just to create video files? The process seems incredibly slow, as it’s only using my CPU instead of my GPU, which makes it so , so slow.

Wouldn’t it be possible to provide the preprocessed video files directly? Or is it necessary to generate them myself? Also, do I even need these training files for the model to work properly, or can I skip this step altogether?

**Comment by zhyjiang** [comment]
LaSOT is only for evaluation. You can run the demo without any training data.
