### ISSUE TITLE
Where is the code for Motion Modeling?

### ISSUE THREAD

**Issue by xuzhichao611** [yangchris11/samurai#54]
I followed the readme and used my video stream to achieve relatively good detection and tracking. Still, I am sorry that I did not find where the innovative Motion Modeling in Samurai is reflected in the code. Please give me some advice.

**Comment by yangchris11** [comment]
The majority of the modifications are made in https://github.com/yangchris11/samurai/blob/master/sam2/sam2/modeling/sam2_base.py. We recommend you to diff with the original SAM 2 repo to get a better idea of the difference we made.
