### ISSUE TITLE
Demo script is failing

### ISSUE THREAD

**Issue by mehtab6028** [yangchris11/samurai#55]
I've cloned this repo in google Colab and installed all the dependencies correctly, ran demo.py script for a demo on custom video by following given instructions. But the cell stops by outputting "^C ", Its surprising to see this as I haven't interrupted the run. I added print statements to see where it is stopping, found that it is stopping after line 70 (demo.py). I've tried further but haven't found any clue why its happening like this. Any recommendations to resolve this ?
 
And i would like to know how i can combine this with yolo.

**Comment by yangchris11** [comment]
Please provide more information on your implementation or issue, so the community can assist you further.

**Comment by zhyjiang** [comment]
I think this issue has the similar problem https://github.com/yangchris11/samurai/issues/28

**Comment by mehtab6028** [comment]
@zhyjiang, yes this is the same problem as #28
