### ISSUE TITLE
Need a detailing on the edges

### ISSUE THREAD

**Issue by pranavatram** [yangchris11/samurai#56]
Need detailing on the edges, otherwise works good to track a person. At first the prepare data set was a bit confusing, for which I had anaylised the script and came up with a code to fill the txt files according to the requirements. Also the eges are too rough, as if it is applying a fast filter. The lack of detailing makes a real case use debatable. Pretty sure with the latest versions there will be refinements into the model and this could be a big thing coming up.

<img width="344" alt="Screenshot 2024-12-02 at 9 03 44 PM" src="https://github.com/user-attachments/assets/79e9321a-735e-4900-a7ac-de6cd63f8968">
<img width="550" alt="Screenshot 2024-12-02 at 9 03 18 PM" src="https://github.com/user-attachments/assets/ea68318a-a5b6-4589-9545-deec4e38c56b">
<img width="253" alt="Screenshot 2024-12-02 at 9 03 31 PM" src="https://github.com/user-attachments/assets/8eaf551d-03b0-4893-88ba-bedcec4fded0">

<img width="544" alt="Screenshot 2024-12-02 at 9 02 58 PM" src="https://github.com/user-attachments/assets/8ae5688f-7373-49a3-95e3-3359bdf8ee50">

**Comment by yangchris11** [comment]
Our main focus is to adapt the existing SAM 2 for visual tracking task. This work [SAM-HQ](https://github.com/SysCV/sam-hq) is probably something you might be interested in.
