### ISSUE TITLE
‘已杀死’ means what?

### ISSUE THREAD

**Issue by zhrli** [yangchris11/samurai#57]
(sam2) lizhaorui@ubuntu:~/DL/samurai$ python scripts/demo.py --video_path DJI.mp4 --txt_path DJI.txt
SAMURAI mode: True
已杀死

DJI.txt is like this:
0.53,0.52,0.02942,0.03657

DJI.mp4 is 2GB , frame size is 3840*2160 

when running, one 4090 nvidia card is occupied with 700MB

**Comment by zhyjiang** [comment]
You may check this issue with a similar problem #28

**Comment by zhyjiang** [comment]
By the way, the bbox coordinates should be in pixel without normalization

**Comment by zhrli** [comment]
> By the way, the bbox coordinates should be in pixel without normalization

thank you, after changing this paras to pixels , it could work for a while.

SAMURAI mode: True
[ WARN:0@212.585] global cap_ffmpeg_impl.hpp:453 _opencv_ffmpeg_interrupt_callback Stream timeout triggered after 31548.078452 ms
[NULL @ 0x562d4cade280] Invalid NAL unit size (298710 > 22381).
[NULL @ 0x562d4cade280] missing picture in access unit with size 22385
已杀死

**Comment by yangchris11** [comment]
@zhrli Please see https://github.com/facebookresearch/sam2/issues/264
