### ISSUE TITLE
SAM2Base.__init__() got an unexpected keyword argument 'samurai_mode'

### ISSUE THREAD

**Issue by Masoudvahid** [yangchris11/samurai#58]
Hi, I’m trying to run demo.py and encountered a few errors. I managed to resolve some, but the last one :
My working directory is the root directory of Samurai.

Errors:

```
hydra.errors.MissingConfigException: Cannot find primary config "configs/samurai/sam2.1_hiera_b+.yaml". Check that it's in your config search path.
Config search path:
	provider=hydra, path=pkg://hydra.conf
	provider=main, path=pkg://sam2
	provider=schema, path=structured://
```
I resolved this by specifying the absolute path to the YAML file.
Afterwards this one pop-up:
```
hydra.errors.InstantiationException: Error in call to target 'sam2.sam2_video_predictor.SAM2VideoPredictor':
TypeError("SAM2Base.__init__() got an unexpected keyword argument 'samurai_mode'")
full_key: model
```

I would appriciate any help to solve this issue

**Comment by hsiangwei0903** [comment]
Did you follow the installation guide? You might need to check your sam2_base.py https://github.com/yangchris11/samurai/blob/fa468e5d40bc4daf208913112950ceb68cb9b239/sam2/sam2/modeling/sam2_base.py#L101 is aligned with our codebase.

**Comment by Masoudvahid** [comment]
Thank you for your reply, I had already fixed by updating sam repo and my environment.

**Comment by JiahaoKou** [comment]
I also encountered the same problem as you, can you share your solution?

**Comment by Masoudvahid** [comment]
Dear @JiahaoKou I created a new env and installed SAM 2 from beginning then I got my solution resolved
