### ISSUE TITLE
Integrate Yolo to initiate the SAMURAI

### ISSUE THREAD

**Issue by sendtohen** [yangchris11/samurai#63]
I would love to use Yolo to initiate the SAMURAI.  I tried, but got errors. 
SAMURAI mode: False
or 
I would get
  File "C:\Users\Documents\samurai\sam2\sam2\modeling\sam2_base.py", line 665, in _prepare_memory_conditioned_features
    iou_score = output_dict["non_cond_frame_outputs"][i]["best_iou_score"]  # Get mask affinity score
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
KeyError: 17

**Comment by hsiangwei0903** [comment]
can you provide more details on your modifications?

**Comment by sendtohen** [comment]
thanks for the suggestion, i will give this method a try.
