### ISSUE TITLE
You're likely running Python from the parent directory of the sam2 repository.

### ISSUE THREAD

**Issue by MiNi650** [yangchris11/samurai#68]
RuntimeError: You're likely running Python from the parent directory of the sam2 repository (i.e. the directory where https://github.com/facebookresearch/sam2 is cloned into). This is not supported since the `sam2` Python package could be shadowed by the repository name (the repository is also named `sam2` and contains the Python package in `sam2/sam2`). Please run Python from another directory (e.g. from the repo dir rather than its parent dir, or from your home directory) after installing SAM 2.

How can i solve this error?

**Comment by yangchris11** [comment]
Don't run it from the parent directory of the sam2 repository, the easiest way is to put your script outside the samurai folder (or create a new one like we did).
