### ISSUE TITLE
Object lost

### ISSUE THREAD

**Issue by kexul** [yangchris11/samurai#69]
https://github.com/user-attachments/assets/b4589417-7ca6-4088-a869-8505ad9226a8

Is there anything I can do to make it better?

**Comment by yangchris11** [comment]
Re-entry is one of the main challenges of visual tracking (well, for any tracking), in your particular case, maybe try adding an extra detector (e.g., https://github.com/IDEA-Research/Grounded-Segment-Anything) to reinitialize your target will be much easier?

**Comment by kexul** [comment]
> Re-entry is one of the main challenges of visual tracking (well, for any tracking), in your particular case, maybe try adding an extra detector (e.g., https://github.com/IDEA-Research/Grounded-Segment-Anything) to reinitialize your target will be much easier?

I've tried vanilla sam2 for tracking, seems to be ok for this case.

**Comment by kexul** [comment]
https://github.com/user-attachments/assets/7477ae72-1bec-4fed-86b3-b634cd38a2c7

**Comment by yangchris11** [comment]
@kexul There will be cases where SAM 2.1 outperforms SAMURAI, maybe you will want to adjust those hyperparameters in https://github.com/yangchris11/samurai/tree/master/sam2/sam2/configs/samurai to see what best fits your use case.

**Comment by kexul** [comment]
> @kexul There will be cases where SAM 2.1 outperforms SAMURAI, maybe you will want to adjust those hyperparameters in https://github.com/yangchris11/samurai/tree/master/sam2/sam2/configs/samurai to see what best fits your use case.

Thanks for you suggestion!
