### ISSUE TITLE
SAMURAI mode: False

### ISSUE THREAD

**Issue by caichuang0415** [yangchris11/samurai#9]
Hello author，
[demo.txt.txt](https://github.com/user-attachments/files/17879679/demo.txt.txt)
thank you very much for your great work.
When I tried your inference script demo.py, I encounter a warning saying "SAMURAI mode: False". Does that mean the inference is using the original sam2 not samurai? If it is, how to solve it ?

**Comment by timHau** [comment]
Hi, i had the the same question.
Not sure if this is correct, but i solved it by changing the paths in the `determine_model_cfg` function in `demo.py` (line 24-38).
Basically changing `sam2.1` --> `samurai`

```python
def determine_model_cfg(model_path):
    if "large" in model_path:
        return "configs/samurai/sam2.1_hiera_l.yaml"
    elif "base_plus" in model_path:
        return "configs/samurai/sam2.1_hiera_b+.yaml"
    elif "small" in model_path:
        return "configs/samurai/sam2.1_hiera_s.yaml"
    elif "tiny" in model_path:
        return "configs/samurai/sam2.1_hiera_t.yaml"
    else:
        raise ValueError("Unknown model size in path!")
```

**Comment by sonoftruth** [comment]
1. Mapping-based Approach:
• Used a dictionary ( config_mapping ) to store model types and their corresponding configuration paths. This simplifies adding or modifying mappings later.
2. Loop:
• Iterates through the mapping to check if the key (e.g.,
"large" ) exists in the model_path . This is more concise and reduces redundant code.
3. Improved Error Handling:
• Includes the problematic model_path in the ValueError for better debugging.

**Comment by yangchris11** [comment]
Fixed in https://github.com/yangchris11/samurai/pull/11, closing the issue.

**Comment by caichuang0415** [comment]
> Hi, i had the the same question. Not sure if this is correct, but i solved it by changing the paths in the `determine_model_cfg` function in `demo.py` (line 24-38). Basically changing `sam2.1` --> `samurai`
> 
> ```python
> def determine_model_cfg(model_path):
>     if "large" in model_path:
>         return "configs/samurai/sam2.1_hiera_l.yaml"
>     elif "base_plus" in model_path:
>         return "configs/samurai/sam2.1_hiera_b+.yaml"
>     elif "small" in model_path:
>         return "configs/samurai/sam2.1_hiera_s.yaml"
>     elif "tiny" in model_path:
>         return "configs/samurai/sam2.1_hiera_t.yaml"
>     else:
>         raise ValueError("Unknown model size in path!")
> ```

OK, thank you I' ll try it
